# Generated by Django 5.0.3 on 2024-03-17 11:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "client",
            },
        ),
        migrations.CreateModel(
            name="GlobalConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("value", models.CharField(max_length=256)),
            ],
            options={
                "db_table": "global_config",
            },
        ),
        migrations.CreateModel(
            name="IntegrationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_name", models.CharField(max_length=50, unique=True)),
                ("status", models.CharField(max_length=50)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrelloBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trello_board_id", models.CharField(max_length=100, unique=True)),
                ("trello_board_name", models.CharField(max_length=100)),
                ("is_working_board", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "trello_board",
            },
        ),
        migrations.CreateModel(
            name="JobCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trello_card_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=300)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_recurring", models.BooleanField(default=False)),
                ("is_owner", models.BooleanField(default=False)),
                ("is_collaborator", models.BooleanField(default=False)),
                ("short_url", models.CharField(max_length=100, unique=True)),
                ("id_short", models.IntegerField()),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wfit.jobcard",
                    ),
                ),
            ],
            options={
                "db_table": "job_card",
            },
        ),
        migrations.CreateModel(
            name="JobTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planned_start", models.DateField(blank=True, null=True)),
                ("planned_finish", models.DateField(blank=True, null=True)),
                ("actual_start", models.DateField(blank=True, null=True)),
                ("actual_finish", models.DateField(blank=True, null=True)),
                ("current_due", models.DateField(blank=True, null=True)),
                ("time_invested", models.IntegerField(blank=True, null=True)),
                (
                    "time_unit",
                    models.CharField(
                        blank=True, default="minutes", max_length=50, null=True
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("being_tracked", models.BooleanField(default=True)),
                (
                    "track_start_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("track_end_date", models.DateField(blank=True, null=True)),
                (
                    "job_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wfit.jobcard"
                    ),
                ),
            ],
            options={
                "db_table": "job_tracker",
            },
        ),
        migrations.CreateModel(
            name="JobLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(default=django.utils.timezone.now)),
                ("time_invested", models.IntegerField()),
                ("time_unit", models.CharField(default="minutes", max_length=50)),
                (
                    "job_tracker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wfit.jobtracker",
                    ),
                ),
            ],
            options={
                "db_table": "job_log",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("label_name", models.CharField(max_length=50, unique=True)),
                ("planned_start", models.DateField(blank=True, null=True)),
                ("planned_finish", models.DateField(blank=True, null=True)),
                ("actual_start", models.DateField(blank=True, null=True)),
                ("actual_finish", models.DateField(blank=True, null=True)),
                ("current_due", models.DateField(blank=True, null=True)),
                ("time_invested", models.IntegerField(blank=True, null=True)),
                (
                    "time_unit",
                    models.CharField(
                        blank=True, default="minutes", max_length=50, null=True
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wfit.client"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wfit.project",
                    ),
                ),
            ],
            options={
                "db_table": "project",
            },
        ),
        migrations.AddField(
            model_name="jobcard",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="wfit.project",
            ),
        ),
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("planned_start", models.DateField(blank=True, null=True)),
                ("planned_finish", models.DateField(blank=True, null=True)),
                ("actual_start", models.DateField(blank=True, null=True)),
                ("actual_finish", models.DateField(blank=True, null=True)),
                ("current_due", models.DateField(blank=True, null=True)),
                ("time_invested", models.IntegerField(blank=True, null=True)),
                (
                    "time_unit",
                    models.CharField(
                        blank=True, default="minutes", max_length=50, null=True
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wfit.project",
                    ),
                ),
            ],
            options={
                "db_table": "release",
            },
        ),
        migrations.AddField(
            model_name="jobtracker",
            name="release",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="wfit.release",
            ),
        ),
        migrations.AddField(
            model_name="jobcard",
            name="trello_board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="wfit.trelloboard"
            ),
        ),
        migrations.CreateModel(
            name="TrelloList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trello_list_id", models.CharField(max_length=100, unique=True)),
                ("trello_list_name", models.CharField(max_length=100)),
                (
                    "workflow_stage",
                    models.IntegerField(
                        choices=[
                            (0, "Undefined"),
                            (1, "Open"),
                            (2, "Ready"),
                            (3, "In Progress"),
                            (4, "Blocked"),
                            (5, "Closed"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wfit.trelloboard",
                    ),
                ),
            ],
            options={
                "db_table": "trello_list",
                "unique_together": {("trello_list_name", "board")},
            },
        ),
        migrations.AddField(
            model_name="jobcard",
            name="trello_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="wfit.trellolist"
            ),
        ),
        migrations.CreateModel(
            name="TrelloLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trello_label_id", models.CharField(max_length=200, unique=True)),
                ("trello_label_name", models.CharField(max_length=100)),
                ("trello_label_color", models.CharField(max_length=100)),
                ("trello_board_id", models.CharField(max_length=200)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wfit.trelloboard",
                    ),
                ),
            ],
            options={
                "db_table": "trello_label",
                "unique_together": {
                    ("trello_label_name", "trello_label_color", "board")
                },
            },
        ),
    ]
