# Generated by Django 5.0.3 on 2024-03-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wfit", "0002_alter_project_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="joblog",
            name="day",
        ),
        migrations.AddField(
            model_name="joblog",
            name="from_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="joblog",
            name="time_from_sessions",
            field=models.IntegerField(db_default=0),
        ),
        migrations.AddField(
            model_name="joblog",
            name="time_from_user",
            field=models.IntegerField(db_default=0),
        ),
        migrations.AddField(
            model_name="joblog",
            name="to_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="joblog",
            name="time_invested",
            field=models.IntegerField(db_default=0),
        ),
        migrations.AlterField(
            model_name="joblog",
            name="time_unit",
            field=models.CharField(db_default="minutes", max_length=50),
        ),
    ]
