# Generated by Django 5.0.3 on 2024-03-17 12:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wfit", "0003_remove_joblog_day_joblog_from_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "time_invested",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("time_unit", models.CharField(default="minutes", max_length=50)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "job_tracker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wfit.jobtracker",
                    ),
                ),
            ],
            options={
                "db_table": "session",
            },
        ),
    ]
