# Generated by Django 5.0.3 on 2024-03-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wfit", "0004_session"),
    ]

    operations = [
        migrations.RenameField(
            model_name="joblog",
            old_name="from_date",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="joblog",
            name="to_date",
        ),
    ]
