# Generated by Django 5.0.3 on 2024-03-17 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wfit", "0005_rename_from_date_joblog_date_remove_joblog_to_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobTrackerJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("journal_date", models.DateField(blank=True, null=True)),
                ("time_from_user", models.IntegerField(db_default=0)),
                ("time_from_sessions", models.IntegerField(db_default=0)),
                ("time_invested", models.IntegerField(db_default=0)),
                ("time_unit", models.CharField(db_default="minutes", max_length=50)),
                (
                    "job_tracker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="wfit.jobtracker",
                    ),
                ),
            ],
            options={
                "db_table": "job_tracker_journal",
            },
        ),
        migrations.DeleteModel(
            name="JobLog",
        ),
    ]
