# Generated by Django 5.0.3 on 2024-03-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wfit", "0006_jobtrackerjournal_delete_joblog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobtrackerjournal",
            name="time_from_sessions",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="jobtrackerjournal",
            name="time_from_user",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="jobtrackerjournal",
            name="time_invested",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="jobtrackerjournal",
            name="time_unit",
            field=models.CharField(default="minutes", max_length=50),
        ),
    ]
