# Generated by Django 5.0.3 on 2024-03-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wfit", "0007_alter_jobtrackerjournal_time_from_sessions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobtrackerjournal",
            name="user_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="jobtrackerjournal",
            unique_together={("job_tracker", "journal_date")},
        ),
    ]
